### ISSUE TITLE
Dissolution chamber giving 2 outputs for 1 recipe for range addons.

### ISSUE THREAD

**Issue by WintersPride** [davqvist/Q-Tech#12] opened 2020-05-05 05:54 UTC
Not sure if intended but it's giving 2 addons for 1 recipe.

**Comment by WintersPride** [comment] 2020-05-05 06:01
it uses an extra bucket of latex but no extra materials*

**Comment by davqvist** [comment] 2020-05-05 06:04
duplicate of #1, the IF dev fixed it yesterday and will be in the next IF update

**Closed as completed by davqvist** 2020-05-05 06:04 UTC
